bromatologia/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path
#Imports de la app
from . import views
#Definimos nuestros Paths

app_name = 'bromatologia'

urlpatterns = [
    path('', views.menu, name='menu'),
    #Habilitacion de negocios
    path('selectContrib', views.selectContrib, name='selectContrib'),
    path('contribNegocios/<int:contribuyente_id>', views.contribNegocios, name='contribNegocios'),
    path('habilitacion_negocios/<int:contribuyente_id>', views.habilNegocios, name='habilNegocios'),
    #Vendedores Ambulantes
    path('selectContrib2', views.selectContrib2, name='selectContrib2'),
    path('contribVendedor/<int:contribuyente_id>', views.contribVendedor, name='contribVendedor'),
    path('habilitacion_vendedor/<int:contribuyente_id>', views.habilVendedor, name='habilVendedor'),
    #Habilitacion remises
    path('selectContrib3', views.selectContrib3, name='selectContrib3'),
    path('contribRemis/<int:contribuyente_id>', views.contribRemis, name='contribRemis'),
    path('habilitacion_remis/<int:contribuyente_id>', views.habilRemis, name='habilRemis'),
    #carnet sanitario
    path('carnet', views.carnet, name='carnet'),
    path('carnet/export/<data>', views.export_pdf, name="export-pdf" ),
]

sir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
#Signup-Login-Logout
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('comercio/', include('comercio.urls')),
    path('contribuyente/', include('contribuyente.urls')),
    path('usuarios/', include('usuario.urls')),
    path('bromatologia/', include('bromatologia.urls')),
    path('rentas/', include('rentas.urls')),
    path('opublicas/', include('opublica.urls')),

    #Admin-User Paths
    url(r'^login/$',auth_views.LoginView.as_view(template_name="admin/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
]

bromatologia/models.py
from django.db import models
from contribuyente.models import Contribuyente

# Create your models here.
class HabilNegocios(models.Model):
    contribuyente = models.ForeignKey(Contribuyente, on_delete=models.CASCADE)
    nota = models.BooleanField('Nota', default=False)
    fotoDNI = models.BooleanField('Fotocopia DNI', default=False)
    fotoCarnet = models.BooleanField('Fotocopia Carnet Sanitario', default=False)
    fotEscritura = models.BooleanField('Fotocopia Título/Contrato de Propiedad', default=False)
    croquis = models.BooleanField('Croquis del Local', default=False)
    libreDeuda = models.BooleanField('Certificado Libre de Deuda', default=False)
    inspeccionComercio = models.BooleanField('Inspección de Comercio', default=False)
    inspeccionObras = models.BooleanField('Inspección de Obras Públicas', default=False)
    matafuego = models.BooleanField('Matafuego', default=False)


class VendedoresAmbulantes(models.Model):
    contribuyente = models.ForeignKey(Contribuyente, on_delete=models.CASCADE)
    nota = models.BooleanField('Nota', default=False)
    carnet = models.BooleanField('Carnet Sanitario', default=False)
    carpa = models.BooleanField('Carpa o Gazebo en buenas condiciones', default=False)
    permiso = models.BooleanField('Permiso del propietario de la vereda', default=False)
    autorizacion = models.BooleanField('Autorización Municipal', default=False)
    certBPM = models.BooleanField('Certificado BPM', default=False)
    agua = models.BooleanField('Poseer Agua Potable', default=False)
    cofia = models.BooleanField('Uniforme y Cofia', default=False)
    

class HabilRemis(models.Model):
    contribuyente = models.ForeignKey(Contribuyente, on_delete=models.CASCADE)
    nota = models.BooleanField('Nota', default=False)
    fotoDNI = models.BooleanField('Fotocopia D.N.I.', default=False)
    fotoSani = models.BooleanField('Fotocopia Carnet Sanitario', default=False)
    fotoCarnet = models.BooleanField('Fotocopia Carnet de Conducir', default=False)
    planilla = models.BooleanField('Planilla Prontuarial', default=False)
    titulo = models.BooleanField('Título del Automotor', default=False)
    contrato = models.BooleanField('Contrato de locación del vehículo o autorización', default=False)
    cedula = models.BooleanField('Cédula Verde', default=False)
    seguro = models.BooleanField('Seguro del Vehículo - Patente', default=False)
    inspeccion = models.BooleanField('Inspección y Desinfección del vehículo', default=False)
    itn = models.BooleanField('Inspección Técnica Nacional', default=False)
    libre = models.BooleanField('Libre de Deuda Municipal', default=False)


class Carnet(models.Model):
    nombre = models.CharField('Nombre', max_length=200)
    dni = models.CharField('L.E. - L.C. - D.N.I.', max_length=200)
    domicilio = models.CharField('Domicilio', max_length=200)
    edad = models.CharField('Edad', max_length=200)
    nacionalidad = models.CharField('Nacionalidad', max_length=200)
    domlaboral = models.CharField('Domicio donde Trabaja', max_length=200)
    presenta = models.CharField('Para ser Presentado', max_length=200)
    estado = models.CharField('Estado', max_length=200)
    profesion = models.CharField('Profesión', max_length=200)
    sangre = models.CharField('Grupo Sanguíneo', max_length=200)

bromatologia/forms.py
# Imports Django
from django import forms

# Imports de la app
from .models import HabilNegocios, VendedoresAmbulantes, HabilRemis, Carnet


class selectContribForm(forms.ModelForm):
    class Meta:
        model = HabilNegocios
        fields = ['contribuyente']


class HabilNegociosForm(forms.ModelForm):
    class Meta:
        model = HabilNegocios
        fields = '__all__'
        exclude = ('contribuyente',)
        

class VendedoresAmbulantesForm(forms.ModelForm):
    class Meta:
        model = VendedoresAmbulantes
        fields = '__all__'
        exclude = ('contribuyente',)


class HabilRemisForm(forms.ModelForm):
    class Meta:
        model = HabilRemis
        fields = '__all__'
        exclude = ('contribuyente',)


class CarnetForm(forms.ModelForm):
    class Meta:
        model = Carnet
        fields = '__all__'
        

bromatologia/views.py
#imports de django
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import HttpResponse
from django.contrib.auth.decorators import permission_required
from django.template.loader import render_to_string
from weasyprint import HTML
from weasyprint.fonts import FontConfiguration

#imports del proyecto
from .forms import HabilNegociosForm
from .forms import selectContribForm
from .forms import VendedoresAmbulantesForm
from .forms import HabilRemisForm
from .forms import CarnetForm
from contribuyente.models import Contribuyente
from .models import HabilNegocios
from .models import VendedoresAmbulantes
from .models import HabilRemis
from .models import Carnet

# Create your views here.

@permission_required('usuarios.ejecutivos')
def menu(request):
    return render(request, 'menu_bromatologia.html', {})


# Habilitación de negocios

@permission_required('usuarios.ejecutivos')
def selectContrib(request):
    form = selectContribForm()
    if request.method == 'POST':
        form = request.POST['contribuyente']
        return redirect('bromatologia:contribNegocios', contribuyente_id=form)
    return render(request, "extras/generic_form.html", {
        'titulo': "Habilitación de Negocios", 
        'form': form, 
        'boton': "Siguiente --->>", })
    

@permission_required('usuarios.ejecutivos')
def habilNegocios(request, contribuyente_id):
    contribuyente = Contribuyente.objects.get(pk=contribuyente_id)
    contribHabil = HabilNegocios.objects.get(contribuyente_id=contribuyente.id)
    form = HabilNegociosForm(instance=contribHabil)
    if form.is_valid():
        form.save()
    contribuyente2 = HabilNegocios.objects.get(contribuyente=contribuyente.id)
    form = HabilNegociosForm(instance=contribuyente2)
    if request.method == 'POST':
        form = HabilNegociosForm(request.POST, instance=contribuyente2)
        if form.is_valid():
            form.save()
            return redirect('bromatologia:contribNegocios', contribuyente_id=contribuyente.id)
    return render(request, "extras/generic_form.html", {
        'titulo': "Habilitación de Negocios", 
        'form': form, 
        'boton': "Guardar", })


@permission_required('usuarios.ejecutivos')
def contribNegocios(request, contribuyente_id):
    contribuyente = HabilNegocios.objects.get(contribuyente_id=contribuyente_id)
    return render(request, 'negocios/contribNegocios.html', {
        'contrib': contribuyente,
        })


# Vendedores Ambulantes

@permission_required('usuarios.ejecutivos')
def selectContrib2(request):
    form = selectContribForm()
    if request.method == 'POST':
        form = request.POST['contribuyente']
        return redirect('bromatologia:contribVendedor', contribuyente_id=form)
    return render(request, "extras/generic_form.html", {
        'titulo': "Vendedores Ambulantes", 
        'form': form, 
        'boton': "Siguiente --->>", })
    

@permission_required('usuarios.ejecutivos')
def habilVendedor(request, contribuyente_id):
    contribuyente = Contribuyente.objects.get(pk=contribuyente_id)
    contribVende = VendedoresAmbulantes.objects.get(contribuyente_id=contribuyente.id)
    form = HabilNegociosForm(instance=contribVende)
    if form.is_valid():
        form.save()
    contribuyente2 = VendedoresAmbulantes.objects.get(contribuyente=contribuyente.id)
    form = VendedoresAmbulantesForm(instance=contribuyente2)
    if request.method == 'POST':
        form = VendedoresAmbulantesForm(request.POST, instance=contribuyente2)
        if form.is_valid():
            form.save()
            return redirect('bromatologia:contribVendedor', contribuyente_id=contribuyente.id)
    return render(request, "extras/generic_form.html", {
        'titulo': "Vendedores Ambulantes", 
        'form': form, 
        'boton': "Guardar", })


@permission_required('usuarios.ejecutivos')
def contribVendedor(request, contribuyente_id):
    contribuyente = VendedoresAmbulantes.objects.get(contribuyente_id=contribuyente_id)
    return render(request, 'negocios/contribVendedor.html', {
        'contrib': contribuyente,
        })


# Habilitación de Remises

@permission_required('usuarios.ejecutivos')
def selectContrib3(request):
    form = selectContribForm()
    if request.method == 'POST':
        form = request.POST['contribuyente']
        return redirect('bromatologia:contribRemis', contribuyente_id=form)
    return render(request, "extras/generic_form.html", {
        'titulo': "Habilitacion para Remises", 
        'form': form, 
        'boton': "Siguiente --->>", })
    

@permission_required('usuarios.ejecutivos')
def habilRemis(request, contribuyente_id):
    contribuyente = Contribuyente.objects.get(pk=contribuyente_id)
    contribRemis = HabilRemis.objects.get(contribuyente_id=contribuyente.id)
    form = HabilRemisForm(instance=contribRemis)
    if form.is_valid():
        form.save()
    contribuyente2 = HabilRemis.objects.get(contribuyente=contribuyente.id)
    form = HabilRemisForm(instance=contribuyente2)
    if request.method == 'POST':
        form = HabilRemisForm(request.POST, instance=contribuyente2)
        if form.is_valid():
            form.save()
            return redirect('bromatologia:contribRemis', contribuyente_id=contribuyente.id)
    return render(request, "extras/generic_form.html", {
        'titulo': "Habilitación para remises", 
        'form': form, 
        'boton': "Guardar", })


@permission_required('usuarios.ejecutivos')
def contribRemis(request, contribuyente_id):
    contribuyente = HabilRemis.objects.get(contribuyente_id=contribuyente_id)
    return render(request, 'negocios/contribRemis.html', {
        'contrib': contribuyente,
        })

#TODO Corregir la generación del PDF para el carnet
#Carnet Sanitario
def carnet(request):
    form = CarnetForm()
    if request.method == 'POST':
        form = CarnetForm(request.POST)
        return redirect('bromatologia:export-pdf', form)
    return render(request, "extras/generic_form.html", {
        'titulo': "Carnet de Sanidad", 
        'form': form, 
        'boton': "Generar", })

def export_pdf(request, data):  
    #context = {}
    html = render_to_string("negocios/carnet.html", data)
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = "inline; report.pdf"
    font_config = FontConfiguration()
    HTML(string=html).write_pdf(response, font_config=font_config)
    return response

bromatologia/templates/negocios/carnet.html
<!doctype html>
<html lang="es">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Reporte PDF</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <style>
        @page {
            size: "A4";
            margin: 1.0cm 1.5cm 3.5cm 1.5cm;
        }
        body {
            width: 100% !important;
            height: 100%;
            background: #fff;
            color: black;
            font-size: 100%;
            font-family: 'Roboto', sans-serif;
            line-height: 1.65;
            -webkit-font-smoothing: antialiased;
            -webkit-text-size-adjust: none; 
        }
        
    </style>
</head>
<body>
<h1 class="text-center">MUNICIPALIDAD DE FRAILE PINTADO</h1>
<br/>
<h2>Veamos que sale</h2>
<table class="table table-bordered" style="text-align: center;">
    <thead class="table-success">
        <th style="text-align: center;">prueba</th>
    </thead>
    <tbody>
        <tr>
            <td>{{ data.nombre.value }}</td>
        </tr>
    </tbody>
</table>

</body>
</html>

bromatologia/templates/negocios/contribNegocios.html
{% extends 'base_bromatologia.html' %}

{% load static %}

{% block body_block %}


<div class="container">
    <div class="row">
        <h2>Contribuyente: <b>{{contrib.contribuyente}}</b></h2>
        <br>
    </div>
    <div class="row">
        <h3>El Contribuyente presentó la siguiente Documentación:</h3>
    </div>
    <div class="row">
        <div class="col col-md-1 offset-1"></div>
        <div class="col col-md-8">
            <table class="table table-bordered" style="text-align: center;">
                <thead class="table-success">
                    <th style="text-align: center;">Documentación</th>
                    <th style="text-align: center;">Estado</th>
                </thead>
                <tbody>
                    <tr>
                        <td>Nota de Solicitud de Habilitación</td>
                        <td>
                            {% if contrib.nota == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Fotocopia del D.N.I.</td>
                        <td>
                            {% if contrib.fotoDNI == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Fotocopia del Carnet Sanitario</td>
                        <td>
                            {% if contrib.fotoCarnet == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Fotocopia de Escritura/Contrato/Permiso de Propiedad</td>
                        <td>
                            {% if contrib.fotoEscritura == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Croquis del Local</td>
                        <td>
                            {% if contrib.croquis == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Certificado de Libre de Deuda Municipal</td>
                        <td>
                            {% if contrib.libreDeuda == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Inspección de Comercio</td>
                        <td>
                            {% if contrib.inspeccionComercio == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Inspección de Obras Públicas</td>
                        <td>
                            {% if contrib.inspeccionObras == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Matafuegos</td>
                        <td>
                            {% if contrib.matafuego == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                </tbody>
            </table>
            <a class="btn btn-primary" href="{% url 'bromatologia:menu' %}"><i class="fa fa-arrow-left"></i>  Volver al Menú</a>
            <a class="btn btn-success" href="{% url 'bromatologia:habilNegocios' contribuyente_id=contrib.id %}"><i class="fa fa-upload"></i>  Cargar Documentación</a>
            <a class="btn btn-warning" href="#"><i class="fa fa-print"></i>  Imprimir</a>
        </div>
        <div class="col col-md-3 offset-3"></div>
    </div>
    <div class="row align-items-center">
        
    </div>
</div>



{% endblock %}

bromatologia/templates/negocios/contribRemis.html
{% extends 'base_bromatologia.html' %}

{% load static %}

{% block body_block %}


<div class="container">
    <div class="row">
        <h2>Contribuyente: <b>{{contrib.contribuyente}}</b></h2>
        <br>
    </div>
    <div class="row">
        <h3>El Contribuyente presentó la siguiente Documentación:</h3>
    </div>
    <div class="row">
        <div class="col col-md-1 offset-1"></div>
        <div class="col col-md-8">
            <table class="table table-bordered" style="text-align: center;">
                <thead class="table-success">
                    <th style="text-align: center;">Documentación</th>
                    <th style="text-align: center;">Estado</th>
                </thead>
                <tbody>
                    <tr>
                        <td>Nota solicitando la habilitación del remis</td>
                        <td>
                            {% if contrib.nota == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Fotocopia del D.N.I.</td>
                        <td>
                            {% if contrib.fotoDNI == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Fotocopia del Carnet Sanitario</td>
                        <td>
                            {% if contrib.fotoSani == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Fotocopia del carnet de conducir</td>
                        <td>
                            {% if contrib.fotoCarnet == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Planilla Prontuarial</td>
                        <td>
                            {% if contrib.planilla == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Título del Automotor</td>
                        <td>
                            {% if contrib.titulo == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Contrato de locación del vehículo o autorización</td>
                        <td>
                            {% if contrib.contrato == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Cédula Verde</td>
                        <td>
                            {% if contrib.cedula == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Seguro del Vehíuculo - Patentamiento</td>
                        <td>
                            {% if contrib.seguro == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Inspección y Desinfección del vehículo</td>
                        <td>
                            {% if contrib.inspeccion == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Inspección Técnica Nacional</td>
                        <td>
                            {% if contrib.itn == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Libre de deuda municipal de ambos (Titular y Chofer)</td>
                        <td>
                            {% if contrib.libre == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                </tbody>
            </table>
            <a class="btn btn-primary" href="{% url 'bromatologia:menu' %}"><i class="fa fa-arrow-left"></i>  Volver al Menú</a>
            <a class="btn btn-success" href="{% url 'bromatologia:habilRemis' contribuyente_id=contrib.id %}"><i class="fa fa-upload"></i>  Cargar Documentación</a>
            <a class="btn btn-warning" href="#"><i class="fa fa-print"></i>  Imprimir</a>
        </div>
        <div class="col col-md-3 offset-3"></div>
    </div>
    <div class="row align-items-center">
        
    </div>
</div>



{% endblock %}

bromatologia/templates/negocios/contribVendedor.html
{% extends 'base_bromatologia.html' %}

{% load static %}

{% block body_block %}


<div class="container">
    <div class="row">
        <h2>Contribuyente: <b>{{contrib.contribuyente}}</b></h2>
        <br>
    </div>
    <div class="row">
        <h3>El Contribuyente presentó la siguiente Documentación:</h3>
    </div>
    <div class="row">
        <div class="col col-md-1 offset-1"></div>
        <div class="col col-md-8">
            <table class="table table-bordered" style="text-align: center;">
                <thead class="table-success">
                    <th style="text-align: center;">Documentación</th>
                    <th style="text-align: center;">Estado</th>
                </thead>
                <tbody>
                    <tr>
                        <td>Nota solicitando la venta ambulante</td>
                        <td>
                            {% if contrib.nota == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Carnet Sanitario</td>
                        <td>
                            {% if contrib.carnet == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Carpa o Gazebo en buenas condiciones</td>
                        <td>
                            {% if contrib.carpa == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Permiso del propietario de la vereda</td>
                        <td>
                            {% if contrib.permiso == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Autorización municipal</td>
                        <td>
                            {% if contrib.autorizacion == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Certificado de BPM</td>
                        <td>
                            {% if contrib.certBPM == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Poseer Agua Potable</td>
                        <td>
                            {% if contrib.agua == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>Uniforme y Cofia</td>
                        <td>
                            {% if contrib.cofia == True %}
                                <b style="color: green;">Presentado</b>
                            {% else %}
                                <b style="color: red;">Faltante</b>
                            {% endif %}
                        </td>
                    </tr>
                </tbody>
            </table>
            <a class="btn btn-primary" href="{% url 'bromatologia:menu' %}"><i class="fa fa-arrow-left"></i>  Volver al Menú</a>
            <a class="btn btn-success" href="{% url 'bromatologia:habilVendedor' contribuyente_id=contrib.id %}"><i class="fa fa-upload"></i>  Cargar Documentación</a>
            <a class="btn btn-warning" href="#"><i class="fa fa-print"></i>  Imprimir</a>
        </div>
        <div class="col col-md-3 offset-3"></div>
    </div>
    <div class="row align-items-center">
        
    </div>
</div>



{% endblock %}