core/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path
#Imports de la app
from . import views
#Definimos nuestros Paths

app_name = 'core'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    ]

sir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
#Signup-Login-Logout
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('comercio/', include('comercio.urls')),
    path('contribuyente/', include('contribuyente.urls')),
    path('usuarios/', include('usuario.urls')),
    path('bromatologia/', include('bromatologia.urls')),
    path('rentas/', include('rentas.urls')),
    path('opublicas/', include('opublica.urls')),

    #Admin-User Paths
    url(r'^login/$',auth_views.LoginView.as_view(template_name="admin/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
]

usuario/urls.py
# Imports de Django
from django.conf.urls import url
from django.urls import path
# Imports de la app
from . import views
from . import autocomplete

# Definimos nuestros Paths

app_name = 'usuarios'
urlpatterns = [
    path('', views.listar_operadores, name='listar_usuarios'),
    #ABM Usuarios
    path('listar/op', views.listar_operadores, name='listar_usuarios'),
    path('crear/op', views.crear_operador, name='crear_usuario'),
    path('modificar/op/<int:operador_id>', views.mod_operador, name='modificar_usuario'),
    path('chpass/op/<int:operador_id>', views.cambiar_password, name='cambiar_password'),
    path('desactivar/op/<int:operador_id>', views.desactivar_usuario, name='desactivar_usuario'),
    path('activar/op/<int:operador_id>', views.activar_usuario, name='activar_usuario'),
    #Autocomplete
    # url(r'^operadores-autocomplete/$', autocomplete.UsuariosAutocomplete.as_view(), name='usuarios-autocomplete',),
]

usuario/models.py
from django.db import models
from django.contrib.auth.models import User
#Imports del proyecto:
from core.choices import TIPO_DOCUMENTOS
#improts de la app
from .choices import NIVELES_SEGURIDAD

# Create your models here.
class Usuario(models.Model):
    nivel_acceso = models.CharField("Acceso de Seguridad", max_length=1, choices=NIVELES_SEGURIDAD, default='O')
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="usuario")
    tipo_doc = models.IntegerField(choices=TIPO_DOCUMENTOS, default=2)
    num_doc = models.CharField('Numero de Documento', unique=True, max_length=100)
    apellidos = models.CharField('Apellidos', max_length=100)
    nombres  = models.CharField('Nombres', max_length=100)
    email = models.EmailField('Correo Electronico')
    telefono = models.CharField('Telefono', max_length=20, default='+549388')
    class Meta:
        verbose_name_plural = 'Usuarios'
        ordering = ['apellidos', 'nombres']
        permissions = (
            #Administador:
            ("admin", "Administrador del Sistema."),
            #Ejecutivo
            ("ejecutivo", "Jefe/Responsable de área"),
            #Empleado
            ("empleado", "Empleado/Operador"),
        )
    def __str__(self):
        return self.apellidos + ', ' + self.nombres

usuario/forms.py
# Imports Python
from datetime import date
# Imports Django
from django.utils import timezone
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import CheckboxSelectMultiple
# Imports extra

# Imports del proyecto
from core.widgets import XDSoftDatePickerInput
# Imports de la app
from .models import Usuario


# Definimos nuestros forms
class CrearUsuarioForm(forms.ModelForm):
    new_user = forms.BooleanField(label="Crear Usuario", initial=False, required=False)

    class Meta:
        model = Usuario
        fields = '__all__'
        exclude = ('usuario',)


class ModUsuarioForm(forms.ModelForm):
    username = forms.CharField(label='Usuario', max_length=15, min_length=6, required=False)
    permisos = forms.MultipleChoiceField(
        label='Permisos',
        widget=CheckboxSelectMultiple(attrs={'class': 'multiplechoice', }),
        required=False,
    )

    class Meta:
        model = Usuario
        fields = '__all__'
        exclude = ('usuario',)

    # Inicializacion
    def __init__(self, *args, **kwargs):
        # Obtenemos permisos
        permisos_list = kwargs.pop('permisos_list', None)
        if permisos_list:
            self.base_fields['permisos'].choices = [(p.id, p.name) for p in permisos_list]
        super(ModUsuarioForm, self).__init__(*args, **kwargs)

    def clean_username(self):
        if not hasattr(self, 'instance') and User.objects.filter(username=self.cleaned_data['username']):
            raise forms.ValidationError(
                "El usuario indicado ya esta en uso, si el usuario tiene mas de una funcion, contacte al administrador")
        return self.cleaned_data['username']

    def clean_email(self):
        if not hasattr(self, 'instance') and User.objects.filter(email=self.cleaned_data['email']):
            raise forms.ValidationError("El mail indicado ya esta en uso, contacte al administrador")
        return self.cleaned_data['email']


class ModPassword(forms.Form):
    username = forms.CharField(label='Usuario', widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    passwd1 = forms.CharField(label="Password", max_length=32, widget=forms.PasswordInput)
    passwd2 = forms.CharField(label="Repetir Password", max_length=32, widget=forms.PasswordInput)

    def clean_passwd2(self):
        passwd1 = self.cleaned_data['passwd1']
        passwd2 = self.cleaned_data['passwd2']
        if passwd1 != passwd2:
            raise forms.ValidationError("Las contraseñas no son iguales")
        return ''

usuario/views.py
#Imports Django
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import permission_required

#Import del proyecto

#Imports de la app
from .functions import obtener_permisos, crear_usuario
from .models import Usuario
from .forms import CrearUsuarioForm
from .forms import ModUsuarioForm, ModPassword

# Create your views here.
@permission_required('usuarios.ejecutivo')
def menu(request):
    return render(request, 'menu_usuarios.html', {})

#Manejo de Usuarios
@permission_required('usuarios.ejecutivo')
def listar_operadores(request):
    usuarios = Usuario.objects.all()
    usuarios = usuarios.select_related('usuario')
    return render(request, 'lista_usuario.html', {
        'usuarios': usuarios,
        'has_table': True,
    })

@permission_required('usuarios.ejecutivo')
def crear_operador(request):
    form = CrearUsuarioForm()
    if request.method == "POST":
        form = CrearUsuarioForm(request.POST)
        if form.is_valid():
            operador = form.save(commit=False)
            #Creamos usuario
            if form.cleaned_data['new_user']:#Si marco el check:
                operador.usuario = crear_usuario(operador)
                operador.save()
                return redirect('usuarios:listar_usuarios')
            #Guardamos
            operador.save()
            return redirect('usuarios:listar_usuarios')
    return render(request, "extras/generic_form.html", {'titulo': "Generar Operador", 'form': form, 'boton': "Crear", })

@permission_required('usuarios.ejecutivo')
def mod_operador(request, operador_id=None):
    operador = None
    form = ModUsuarioForm(permisos_list=obtener_permisos(),)
    if operador_id:
        #Si es para modificar conseguimos las bases
        operador = Usuario.objects.get(pk=operador_id)
        usuario = operador.usuario
        permisos_habilitados = [p for p in obtener_permisos(usuario=request.user)]
        id_permisos_habilitados = [p.id for p in obtener_permisos(usuario=usuario)]
        if usuario:
            #Generamos el form
            form = ModUsuarioForm(
                instance=operador,
                permisos_list=permisos_habilitados,
                initial={
                    'username': usuario.username,
                    'permisos': id_permisos_habilitados,
            })
        else:
            form = ModUsuarioForm(
                instance=operador,
                permisos_list=permisos_habilitados,
            )
    if request.method == "POST":
        form = ModUsuarioForm(request.POST, instance=operador)
        if form.is_valid():
            operador = form.save(commit=False)
            #Si nos dio un username
            if form.cleaned_data['username']:
                if not operador.usuario:
                    operador.usuario = crear_usuario(operador)
                    operador.save()
                if operador.usuario.username != form.cleaned_data['username']:
                    operador.usuario.username = form.cleaned_data['username']
                    operador.usuario.save()
            #Reiniciamos sus permisos:
            if usuario:
                for permiso in obtener_permisos():
                    usuario.user_permissions.remove(permiso)
                for permiso in request.POST.getlist('permisos'):
                    usuario.user_permissions.add(permiso)
                usuario.save()
            operador.save()
            return redirect('usuarios:listar_usuarios')
    return render(request, "extras/generic_form.html", {'titulo': "Modificar datos de Usuario", 'form': form, 'boton': "Guardar", })

@permission_required('operadores.operador_admin')
def cambiar_password(request, operador_id):
    operador = Usuario.objects.get(pk=operador_id)
    usuario = operador.usuario
    form = ModPassword(initial={'username': usuario.username, })
    if request.method == 'POST':
        form = ModPassword(request.POST)
        if form.is_valid():
            usuario.password = make_password(form.cleaned_data['passwd1'])
            usuario.save()
            return redirect('usuarios:listar_usuarios')
    #Sea por ingreso o por salida:
    return render(request, "extras/generic_form.html", {'titulo': "Modificar Usuario", 'form': form, 'boton': "Modificar", })

@permission_required('operadores.operador_admin')
def desactivar_usuario(request, operador_id):
    operador = Usuario.objects.get(pk=operador_id)
    usuario = operador.usuario
    usuario.is_active = False
    usuario.save()
    return redirect('usuarios:listar_usuarios')

@permission_required('operadores.operador_admin')
def activar_usuario(request, operador_id):
    operador = Usuario.objects.get(pk=operador_id)
    usuario = operador.usuario
    usuario.is_active = True
    usuario.save()
    return redirect('usuarios:listar_usuarios')

usuario/templates/base_usuarios.html
{% extends 'sistema/base.html' %}

{% load static %}


{% block custom_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/operadores.css' %}" />
{% endblock %}

{% block body_block %}

{% endblock %}

{% block custom_script %}

{% endblock %}

usuario/templates/info_user.html
{% load operadores_tags %}
{% block body_block %}
    <div class="info_user card" style="text-align: center;">
        <div class="card-header bg-warning">
            {% ct_get_operador request as operador %}
            <p><b>{{operador.apellidos}}, {{operador.nombres}}</b></p>
        </div>
        <div class="card-body">
            <p>
            {% if operador.tipo_doc == 1 %}
                <b>C.I. :
            {% elif operador.tipo_doc == 2 %}
                <b>D.N.I. :
            {% elif operador.tipo_doc == 3 %}
                <b>L.C. :
            {% elif operador.tipo_doc == 4 %}
                <b>L.E. :
            {% else %}
                <b>PASSPORTE :
            {% endif %}
            </b> {{operador.num_doc}}</p>
            <p><b>Usuario:</b> {{request.user.username}}</b></p>
        </div>
        <div class="card-footer bg-secondary">
            <a class="btn btn-outline-primary" href="{% url 'core:home' %}">Volver al Menú Principal</a>
        </div>
    </div>
    
{% endblock %}

usuario/templates/lista_usuario.html
{% extends 'base_usuarios.html' %}

{% load adminusers_tags %}

{% block body_block %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">
                    <h1>Listado de Usuarios: <b>{{app_name}}</b></h1>
                </div>
                <div class="row">
                <p style="float:right;">
                        {% if perms.usuarios.operadores %}
                            <a class="btn btn-outline-info" href="{% url 'usuarios:crear_usuario' %}">
                                Crear Usuario
                                <img class="icons" src="/static/admin/img/icon-addlink.svg" alt="Crear Nuevo Usuario">
                            </a>
                        {% endif %}
                    </p><br><br>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-striped table-bordered" id="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Usuario</th>
                                    <th>Num Documento</th>
                                    <th>Operador</th>
                                    <th>Nivel Autorizacion</th>
                                    <th>Telefono</th>
                                    <th>Email</th>
                                    <th>Estado</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for operador in usuarios %}
                                    <tr class="fila_usuario">
                                        <td>{{operador.usuario.username}}</td>
                                        <td>{{operador.num_doc}}</td>
                                        <td>
                                            {{operador.apellidos}}, {{operador.nombres}}
                                        </td>
                                        <td>{{operador.get_nivel_acceso_display}}</td>
                                        <td>{{operador.telefono}}</td>
                                        <td>{{operador.email}}</td>
                                        <td><!-- Icono de Activo -->
                                            {% if operador.usuario.is_active %}
                                                <b style="color:green;">Activo</b>
                                            {% else %}
                                                <b style="color:red;">Inactivo</b>
                                            {% endif %}
                                        </td>
                                        <td><!-- Acciones -->
                                            <a class="nolink" href="{% url 'usuarios:modificar_usuario' operador_id=operador.id %}">
                                                <img class="icons" src="/static/admin/img/icon-changelink.svg" alt="Modificar">
                                                Modificar
                                            </a><br>
                                            {% if operador.usuario %}
                                                <a class="nolink" href="{% url 'usuarios:cambiar_password' operador_id=operador.id %}">
                                                    <img class="icons" src="/static/admin/img/icon-alert.svg" alt="Cambiar contraseña">
                                                    Cambiar Clave
                                                </a><br>
                                                {% if operador.usuario.is_active %}
                                                    <a class="nolink" href="{% url 'usuarios:desactivar_usuario' operador_id=operador.id %}">
                                                        <img class="icons" src="/static/admin/img/icon-deletelink.svg" alt="Desactivar">
                                                        Desactivar
                                                    </a><br>
                                                {% else %}
                                                    <a class="nolink" href="{% url 'usuarios:activar_usuario' operador_id=operador.id %}">
                                                        <img class="icons" src="/static/admin/img/icon-yes.svg" alt="Activar">
                                                        Activar
                                                    </a>
                                                {% endif %}

                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

usuario/templates/menu_usuarios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>