bromatologia/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path
#Imports de la app
from . import views
#Definimos nuestros Paths

app_name = 'bromatologia'

urlpatterns = [
    path('', views.menu, name='menu'),
    #Habilitacion de negocios
    path('selectContrib', views.selectContrib, name='selectContrib'),
    path('contribNegocios/<int:contribuyente_id>', views.contribNegocios, name='contribNegocios'),
    path('habilitacion_negocios/<int:contribuyente_id>', views.habilNegocios, name='habilNegocios'),
    #Vendedores Ambulantes
    path('selectContrib2', views.selectContrib2, name='selectContrib2'),
    path('contribVendedor/<int:contribuyente_id>', views.contribVendedor, name='contribVendedor'),
    path('habilitacion_vendedor/<int:contribuyente_id>', views.habilVendedor, name='habilVendedor'),
    #Habilitacion remises
    path('selectContrib3', views.selectContrib3, name='selectContrib3'),
    path('contribRemis/<int:contribuyente_id>', views.contribRemis, name='contribRemis'),
    path('habilitacion_remis/<int:contribuyente_id>', views.habilRemis, name='habilRemis'),
    #carnet sanitario
    path('carnet', views.carnet, name='carnet'),
    path('carnet/export/<data>', views.export_pdf, name="export-pdf" ),
]

comercio/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path
#Imports de la app
from . import views
#Definimos nuestros Paths

app_name = 'comercio'
urlpatterns = [
    path('', views.index, name='index'),

    #Impuestos
    path('impuestos/',views.lista_impuestos, name='lista_impuestos'),
    path('impuestos/crear',views.crear_impuesto, name='crear_impuestos'),
    ]

core/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path
#Imports de la app
from . import views
#Definimos nuestros Paths

app_name = 'core'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    ]

opublica/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path
#Imports de la app
from . import views
#Definimos nuestros Paths

app_name = 'opublicas'
urlpatterns = [
    path('', views.menu, name='menu'),
    ]

sir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
#Signup-Login-Logout
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('comercio/', include('comercio.urls')),
    path('contribuyente/', include('contribuyente.urls')),
    path('usuarios/', include('usuario.urls')),
    path('bromatologia/', include('bromatologia.urls')),
    path('rentas/', include('rentas.urls')),
    path('opublicas/', include('opublica.urls')),

    #Admin-User Paths
    url(r'^login/$',auth_views.LoginView.as_view(template_name="admin/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
]

usuario/urls.py
# Imports de Django
from django.conf.urls import url
from django.urls import path
# Imports de la app
from . import views
from . import autocomplete

# Definimos nuestros Paths

app_name = 'usuarios'
urlpatterns = [
    path('', views.listar_operadores, name='listar_usuarios'),
    #ABM Usuarios
    path('listar/op', views.listar_operadores, name='listar_usuarios'),
    path('crear/op', views.crear_operador, name='crear_usuario'),
    path('modificar/op/<int:operador_id>', views.mod_operador, name='modificar_usuario'),
    path('chpass/op/<int:operador_id>', views.cambiar_password, name='cambiar_password'),
    path('desactivar/op/<int:operador_id>', views.desactivar_usuario, name='desactivar_usuario'),
    path('activar/op/<int:operador_id>', views.activar_usuario, name='activar_usuario'),
    #Autocomplete
    # url(r'^operadores-autocomplete/$', autocomplete.UsuariosAutocomplete.as_view(), name='usuarios-autocomplete',),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
#Imports Django
from django.shortcuts import render, redirect
from django.contrib.admin.views.decorators import staff_member_required
#Imports del proyecto

#Imports de la app


# Create your views here.

def home(request):
    return render(request, 'home.html')

core/templates/home.html
{% extends 'sistema/base.html' %}

{% load static %}

{% block body_block %}

<header class="bg-primary text-white text-center" style="padding-top: -100px;">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img class="masthead-avatar mb-5" src="{% static 'assets/img/frailePintado.png' %}" alt="" />
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">SISTEMA INTEGRAL DE RENTAS</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->
        <p class="masthead-subheading font-weight-light mb-3">Municipalidad de Fraile Pintado</p>
    </div>
</header>
<!-- Menu Principal -->
{% include 'menu_principal.html' %}

{% endblock %}

core/templates/menu_principal.html
{% load static %}

<section class="page-section portfolio" id="portfolio">
    <div class="container">
        <!-- Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Secciones</h2>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Grid Items-->
        <div class="row">
            <!-- Item 1-->
            <div class="col-md-6 col-lg-4 mb-5 mb-lg-0">
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Rentas</h2>
                    <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal4">
                        <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                            <a href="#">
                            <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-sign-in-alt fa-3x"></i></div>
                        </div>
                        <img class="img-fluid" src="{% static 'assets/img/portfolio/game.png' %}" alt="" />
                        </a>
                    </div>
                </div>
            
            <!-- Item 2-->
            <div class="col-md-6 col-lg-4 mb-5">
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Comercio</h2>
                <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal1">
                    <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                        <a href="{% url 'comercio:index' %}">
                        <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-sign-in-alt fa-3x"></i></div>
                    </div>
                    <img class="img-fluid" src="{% static 'assets/img/portfolio/cabin.png' %}" alt="" />
                    </a>
                </div>
            </div>
            <!-- Item 3-->
            <div class="col-md-6 col-lg-4 mb-5">
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Bromatología</h2>
                <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal3">
                    <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                        <a href="{% url 'bromatologia:menu' %}">
                        <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-sign-in-alt fa-3x"></i></div>
                    </div>
                    <img class="img-fluid" src="{% static 'assets/img/portfolio/circus.png' %}" alt="" />
                </div>
            </div>
            <!-- Item 4-->
            <div class="col-md-6 col-lg-4 mb-5">
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Contribuyentes</h2>
                    <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal2">
                        <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                            <a href="{% url 'contribuyentes:menu' %}">
                            <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-sign-in-alt fa-3x"></i></div>
                        </div>
                        <img class="img-fluid" src="{% static 'assets/img/portfolio/cake.png' %}" alt="" />
                        </a>
                    </div>
                </div>
            <!-- Item 5-->
            <div class="col-md-6 col-lg-4 mb-5 mb-md-0">
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Obras Públicas</h2>
                <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal5">
                    <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                        <a href="{% url 'opublicas:menu' %}">
                        <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-sign-in-alt fa-3x"></i></div>
                    </div>
                    <img class="img-fluid" src="{% static 'assets/img/portfolio/safe.png' %}" alt="" />
                    </a>
                </div>
            </div>
            <!-- Item 6-->
            <div class="col-md-6 col-lg-4 mb-5 mb-md-0">
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Usuarios</h2>
                <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal6">
                    <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                        <a href="{% url 'usuarios:listar_usuarios' %}">
                        <div class="portfolio-item-caption-content text-center text-white">
                            <i class="fas fa-sign-in-alt fa-3x"></i></div>  
                        </div>                  
                        <img class="img-fluid" src="{% static 'assets/img/portfolio/usuarios.png' %}" alt="" />
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>