contribuyente/urls.py
# Imports de Django
from django.conf.urls import url
from django.urls import path
# Imports de la app
from . import views

# Definimos nuestros Paths
from .views import *

app_name = 'contribuyentes'
urlpatterns = [
    path('', views.menu, name='menu'),
    path('lista_contrib', views.lista_contribuyentes, name='lista_contribuyentes'),
    path('cargar_contrib', views.cargar_contribuyente, name='cargar_contribuyente'),
    path('mod_contrib/<int:contribuyente_id>', views.cargar_contribuyente, name='mod_contribuyente'),
    path('activar/<int:contribuyente_id>', views.activar_contribuyente, name='activar_contribuyente'),
    path('baja/<int:contribuyente_id>', views.baja_contribuyente, name='baja_contribuyente'),

    # Angular
    url(r'^api/contrib$', ContribuyenteAPIview.as_view(), name='contrib'),
    path('api/contrib/<int:numDoc>', views.contrib_detail),
]

sir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
#Signup-Login-Logout
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('comercio/', include('comercio.urls')),
    path('contribuyente/', include('contribuyente.urls')),
    path('usuarios/', include('usuario.urls')),
    path('bromatologia/', include('bromatologia.urls')),
    path('rentas/', include('rentas.urls')),
    path('opublicas/', include('opublica.urls')),

    #Admin-User Paths
    url(r'^login/$',auth_views.LoginView.as_view(template_name="admin/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
]

contribuyente/models.py
from django.db import models
from .choices import TIPO_DOC, ESTADOS_CONTRIB
from core.choices import NACIONALIDADES
from django.urls import reverse
from django.utils import timezone

# Create your models here.
class Contribuyente(models.Model):
    apellido = models.CharField("Apellido", max_length=100)
    nombre = models.CharField("Nombres", max_length=200)
    tipoDoc = models.CharField("Tipo Doc", max_length=3, choices=TIPO_DOC, default='DNI')
    numDoc = models.IntegerField("Num Documento", null=False, blank=False, default=0)
    fecNac = models.DateField("Fecha Nacimiento", default=timezone.now)
    nacionalidad = models.IntegerField("nacionalidad", choices=NACIONALIDADES, default=200)
    estado = models.IntegerField("Estado", choices=ESTADOS_CONTRIB, default=1)


    class Meta:
        verbose_name = "Contribuyente"
        verbose_name_plural = "Contribuyentes"


    def __str__(self):
        return self.apellido + ', ' + self.nombre

    def get_absolute_url(self):
        return reverse("Contribuyente_detail", kwargs={"pk": self.pk})

contribuyente/forms.py
# Imports Python
from datetime import date
# Imports Django
from django.utils import timezone
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import CheckboxSelectMultiple
# Imports extra

# Imports del proyecto
from core.widgets import XDSoftDatePickerInput
# Imports de la app
from .models import Contribuyente


class ContribuyenteForm(forms.ModelForm):    
    class Meta:
        model = Contribuyente
        fields = '__all__'
        widgets = {
            'fecNac': XDSoftDatePickerInput(attrs={'autocomplete':'on'}),
        }

contribuyente/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.parsers import JSONParser
from rest_framework.response import Response
from rest_framework import generics, mixins
from django.views.decorators.csrf import csrf_exempt
from .serializer import ContribuyenteSerializer
from .models import Contribuyente
from .forms import ContribuyenteForm
from core.choices import NACIONALIDADES
from django.contrib.auth.decorators import permission_required
from .functions import cargarCaracteristicas
from django.db.models import Q


# Create your views here.
@permission_required('usuarios.ejecutivos')
def menu(request):
    return render(request, 'menu_contribuyentes.html', {})


@permission_required('usuarios.ejecutivos')
def lista_contribuyentes(request):
    contribuyentes = Contribuyente.objects.all()
    for i in contribuyentes:
        for j in NACIONALIDADES:
            if i.nacionalidad == j[0]:
                i.nacionalidad = j[1]
    return render(request, 'lista_contribuyentes.html', {
        'contribuyentes': contribuyentes,
        'has_table': True,
    })


@permission_required('usuarios.ejecutivos')
def cargar_contribuyente(request, contribuyente_id=None):
    contribuyente = None
    if contribuyente_id:
        contribuyente = Contribuyente.objects.get(pk=contribuyente_id)
        form = ContribuyenteForm(instance=contribuyente)
        if request.method == 'POST':
            form = ContribuyenteForm(request.POST, instance=contribuyente)
            if form.is_valid():
                form.save()
                return redirect('contribuyentes:lista_contribuyentes')
    else:
        form = ContribuyenteForm()
        if request.method == 'POST':
            form = ContribuyenteForm(request.POST)
            if form.is_valid():
                form.save()
                nuevo = form['numDoc'].value()
                nuevoContrib = Contribuyente.objects.filter(numDoc=nuevo).first()
                valor = str(nuevoContrib.id)
                cargarCaracteristicas(valor)
                return redirect('contribuyentes:lista_contribuyentes')
    return render(request, "extras/generic_form.html",
                  {'titulo': "Cargar Contribuyente", 'form': form, 'boton': "Guardar", })


@permission_required('usuarios.ejecutivos')
def baja_contribuyente(request, contribuyente_id):
    contribuyente = Contribuyente.objects.get(pk=contribuyente_id)
    contribuyente.estado = 0
    contribuyente.save()
    return redirect('contribuyentes:lista_contribuyentes')


@permission_required('usuarios.ejecutivos')
def activar_contribuyente(request, contribuyente_id):
    contribuyente = Contribuyente.objects.get(pk=contribuyente_id)
    contribuyente.estado = 1
    contribuyente.save()
    return redirect('contribuyentes:lista_contribuyentes')


@api_view(['GET', 'POST', 'DELETE'])
def contrib_list(request):
    contribuyente = Contribuyente.objects.all().values()
    return JsonResponse({'contribuyentes': list(contribuyente)})


@api_view(['GET', 'PUT', 'DELETE'])
def contrib_detail(request, numDoc):
    try:
        if request.method == 'GET':
            contribuyente = Contribuyente.objects.filter(numDoc=numDoc).values()
            return JsonResponse({'contribuyentes': list(contribuyente)})
    except Contribuyente.DoesNotExist:
        return JsonResponse({'message': 'El contribuyente no existe'}, status=status.HTTP_404_NOT_FOUND)


class ContribuyenteAPIview(mixins.CreateModelMixin, generics.ListAPIView):
    lookup_field = "pk"
    serializer_class = ContribuyenteSerializer

    def get_queryset(self):
        qs = Contribuyente.objects.all()
        query = self.request.GET.get("q")
        if query is not None:
            qs = qs.filter(
                Q(numDoc=query)
            ).distinct()
        return qs

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

contribuyente/templates/base_contribuyentes.html
{% extends 'sistema/base.html' %}

{% load static %}


{% block custom_head %}
    
{% endblock %}

{% block body_block %}

{% endblock %}

{% block custom_script %}

{% endblock %}

contribuyente/templates/lista_contribuyentes.html
{% extends 'base_contribuyentes.html' %}

{% load adminusers_tags %}

{% block body_block %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">
                    <h1>Listado de Contribuyentes: <b>{{app_name}}</b></h1>
                </div>
                <div class="row">
                <p style="float:right;">
                        {% if perms.usuarios.operadores %}
                            <a class="btn btn-outline-info" href="{% url 'contribuyentes:cargar_contribuyente' %}">
                                Cargar Contribuyente
                                <img class="icons" src="/static/admin/img/icon-addlink.svg" alt="Cargar Nuevo Contribuyente">
                            </a>
                        {% endif %}
                    </p><br><br>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-striped table-bordered" id="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Apellido</th>
                                    <th>Nombres</th>
                                    <th>Tipo de Doc.</th>
                                    <th>Num. Doc.</th>
                                    <th>Fecha de Nac.</th>
                                    <th>Nacionalidad</th>
                                    <th>Estado</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for x in contribuyentes %}
                                    <tr class="fila_usuario">
                                        <td>{{x.apellido}}</td>
                                        <td>{{x.nombre}}</td>
                                        <td>{{x.tipoDoc}}</td>
                                        <td>{{x.numDoc}}</td>
                                        <td>{{x.fecNac}}</td>
                                        <td>{{x.nacionalidad}}</td>
                                        <td><!-- Icono de Activo -->
                                            {% if x.estado == 1 %}
                                                <b style="color:green;">Activo</b>
                                            {% else %}
                                                <b style="color:red;">Baja</b>
                                            {% endif %}
                                        </td>
                                        <td><!-- Acciones -->
                                            <a class="nolink" href="{% url 'contribuyentes:mod_contribuyente' contribuyente_id=x.id %}">
                                                <img class="icons" src="/static/admin/img/icon-changelink.svg" alt="Modificar">
                                                Modificar
                                            </a><br>
                                                {% if x.estado == 1 %}
                                                    <a class="nolink" href="{% url 'contribuyentes:baja_contribuyente' contribuyente_id=x.id %}">
                                                        <img class="icons" src="/static/admin/img/icon-deletelink.svg" alt="Desactivar">
                                                        Dar de Baja
                                                    </a><br>
                                                {% else %}
                                                    <a class="nolink" href="{% url 'contribuyentes:activar_contribuyente' contribuyente_id=x.id %}">
                                                        <img class="icons" src="/static/admin/img/icon-yes.svg" alt="Activar">
                                                        Activar
                                                    </a>
                                                {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

contribuyente/templates/menu_contribuyentes.html
{% extends 'sistema/base.html' %}

{% load static %}

{% block body_block %}
<section class="resumen">
    <section class="informacion_basica">
        <div class="container">
            <div class="row">   
                <div class="col-md-8 align-self-center offset-1">     
                    <h1>Menu Contribuyentes:</h1>
                </div>
                <div class="col-md-3">
                    <br>
                    {% include 'info_user.html' %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <ul class="menu_botones">
                        <li><a href="{% url 'contribuyentes:lista_contribuyentes'  %}">Lista de Contribuyentes</a></li>
                        <hr>
                    </ul>
                </div>
            </div>
        </div>
    </section>
</section>
{% endblock %}